#!/usr/bin/env python3
"""
Compute the model's flash footprint by summing every const-qualified array
declared in the codegen output (genModel.h + genModel.c). These are the
read-only arrays that go to flash on an MCU; on wasm they end up in the data
section. Non-const arrays (the mutable sparse-update weights aliased into
buffer0/SRAM) are deliberately excluded — they live in RAM, not flash.

Usage:
    python tools/compute_flash.py <model_name>

Reads:
    codegen-<model>/include/genModel.h
    codegen-<model>/source/genModel.c
Writes:
    codegen-<model>/flash_bytes.zig    (pub const flash_bytes: u32 = N;)

The Zig file is imported by build.zig to populate `-DMODEL_SIZE_VALUE` for
each model, replacing the upstream `#define MODEL_SIZE` number (which doesn't
match a clean "sum of flash-resident bytes" interpretation).
"""

import re
import sys
from pathlib import Path

# Byte widths for the C types tinyengine's codegen emits at file scope.
TYPE_BYTES = {
    "char": 1,
    "signed char": 1,
    "unsigned char": 1,
    "int8_t": 1,
    "uint8_t": 1,
    "int16_t": 2,
    "uint16_t": 2,
    "int32_t": 4,
    "uint32_t": 4,
    "float": 4,
    "double": 8,
}
TYPE_PATTERN = r"(?:unsigned char|signed char|u?int(?:8|16|32)_t|float|double|char)"

# Matches a single-line const array declaration with one or more dimensions.
# Examples this matches:
#   const float bias_fp0[16] = { ... };
#   const unsigned char weight12[1024] = { ... };
#   const int32_t offsetRBias3[40] = { ... };
#   const float foo[3][5];
ARRAY_RE = re.compile(rf"^const\s+({TYPE_PATTERN})\s+(\w+)((?:\[\d+\])+)")
DIMS_RE = re.compile(r"\[(\d+)\]")


def sum_const_arrays(text, into):
    """Scan text for const array decls; merge into `into` dict (keyed by name)."""
    for line in text.splitlines():
        m = ARRAY_RE.match(line.lstrip())
        if not m:
            continue
        ctype, name, dims_str = m.group(1), m.group(2), m.group(3)
        if ctype not in TYPE_BYTES:
            continue
        elems = 1
        for d in DIMS_RE.findall(dims_str):
            elems *= int(d)
        bytes_total = elems * TYPE_BYTES[ctype]
        # Dedupe by name (extern decl in .h + definition in .c shouldn't double-count).
        prev = into.get(name)
        if prev is not None and prev != bytes_total:
            sys.stderr.write(f"  ! conflicting sizes for '{name}': {prev} vs {bytes_total} — using max\n")
            into[name] = max(prev, bytes_total)
        else:
            into[name] = bytes_total


def main():
    if len(sys.argv) != 2:
        sys.stderr.write(f"usage: {sys.argv[0]} <model_name>\n")
        return 2
    model = sys.argv[1]
    project_dir = Path(__file__).resolve().parent.parent
    cg_dir = project_dir / f"codegen-{model}"
    gen_h = cg_dir / "include" / "genModel.h"
    gen_c = cg_dir / "source" / "genModel.c"
    if not gen_h.is_file() or not gen_c.is_file():
        sys.stderr.write(f"missing codegen for {model}: expected {gen_h} and {gen_c}\n")
        return 2

    arrays = {}
    sum_const_arrays(gen_h.read_text(), arrays)
    sum_const_arrays(gen_c.read_text(), arrays)

    total = sum(arrays.values())
    out_path = cg_dir / "flash_bytes.zig"
    out_path.write_text(
        "// Auto-generated by tools/compute_flash.py — do not edit by hand.\n"
        "// Sum of every const-qualified array in genModel.h + genModel.c\n"
        "// (the flash-resident bytes; mutable sparse-update copies in SRAM are\n"
        "// excluded). Imported by build.zig as MODEL_SIZE_VALUE.\n"
        f"pub const flash_bytes: u32 = {total};\n"
    )
    sys.stderr.write(f"✓ wrote flash_bytes.zig for {model}: {len(arrays)} const arrays, {total} bytes\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
