#!/usr/bin/env python3
"""
Generate codegen-MODEL/source/te_snapshot.c by inspecting the freshly-emitted
codegen-MODEL/source/genModel.c and codegen-MODEL/include/genModel.h.

The snapshot table covers every v* trainable tensor — defined as one that
either gets `-=` mutated in genModel.c's invoke(labels) backward block or
appears as a weight argument to a sparse-update kernel call (group_pointwise
or group_conv_fp kernels with the QAS+lr trailing args).

Usage:
    python tools/extract_snapshot.py <model_name>

Reads:
    codegen-<model>/source/genModel.c
    codegen-<model>/include/genModel.h
Writes:
    codegen-<model>/source/te_snapshot.c

The codegen task normalizes tinyengine's PascalCase Source/+Include/ dirs to
lowercase before this runs. Both inputs live in the zig-te-train1 project
(no upstream files touched).
"""

import os
import re
import sys
from pathlib import Path


def extract(model):
    project_dir = Path(__file__).resolve().parent.parent
    cg_dir = project_dir / f"codegen-{model}"
    gen_c = cg_dir / "source" / "genModel.c"
    gen_h = cg_dir / "include" / "genModel.h"
    out_c = cg_dir / "source" / "te_snapshot.c"
    if not gen_c.is_file() or not gen_h.is_file():
        sys.stderr.write(f"missing codegen for {model}: expected {gen_c} and {gen_h}\n")
        return 2

    # 1) Mutation sites in genModel.c: collect every v*_bias / v*_weight that
    #    appears on the LHS of `-= ` or as the int8-weight arg in a sparse
    #    kernel call.
    mutated = set()
    src = gen_c.read_text()
    for ln in src.splitlines():
        m = re.search(r"\b(v\d+(?:_conv_\d+)?_(?:weight|bias))\[i\]\s*-=", ln)
        if m:
            mutated.add(m.group(1))
        m = re.search(r"group_pointwise_conv_fp\b.*[^A-Za-z](v\d+(?:_conv_\d+)?_weight)\b", ln)
        if m:
            mutated.add(m.group(1))
        m = re.search(r"group_conv_fp_kernel.*[^A-Za-z](v\d+(?:_conv_\d+)?_weight)\b", ln)
        if m:
            mutated.add(m.group(1))

    if not mutated:
        # fwd-only codegen — no trainable tensors. Emit stubs.
        out_c.write_text(_stub_te_snapshot(model))
        sys.stderr.write(f"✓ wrote stub te_snapshot.c for {model} (fwd-only)\n")
        return 0

    # 2) Map each v* alias to its underlying weightN / biasN / offsetRBiasN
    #    storage and look up the storage size from genModel.h.
    head = gen_h.read_text()
    size_map = {}  # storage_name -> (elem_type, count)
    alias_map = {}  # v_name -> (storage_name, elem_type, is_const)
    for ln in head.splitlines():
        m = re.match(r"^(const\s+)?(unsigned char|int32_t)\s+(weight\d+|bias\d+|offsetRBias\d+)\[(\d+)\]", ln)
        if m:
            size_map[m.group(3)] = (m.group(2), int(m.group(4)))
            continue
        m = re.match(r"^(const\s+)?(unsigned char|int32_t)\s*\*\s*(v\w+)\s*=\s*(\w+);", ln)
        if m:
            alias_map[m.group(3)] = (m.group(4), m.group(2), bool(m.group(1)))

    head_idx = max(int(re.match(r"v(\d+)", t).group(1)) for t in mutated)

    entries = []  # list of (storage, bytes, is_head, is_weight, alias)
    total = 0
    for t in sorted(mutated, key=lambda x: (int(re.match(r"v(\d+)", x).group(1)), x)):
        if t not in alias_map:
            sys.stderr.write(f"  ! no alias for {t}; skipping\n")
            continue
        u = alias_map[t][0]
        if u not in size_map:
            sys.stderr.write(f"  ! no size for {u} (alias {t}); skipping\n")
            continue
        elem_t, n = size_map[u]
        nb = n * (1 if elem_t == "unsigned char" else 4)
        is_head = 1 if t.startswith(f"v{head_idx}_") else 0
        is_weight = 1 if t.endswith("_weight") else 0
        entries.append((u, nb, is_head, is_weight, t))
        total += nb

    out_c.write_text(_render_te_snapshot(model, entries, total))
    sys.stderr.write(
        f"✓ wrote te_snapshot.c for {model}: {len(entries)} trainable tensors, "
        f"{total} bytes (head={'v' + str(head_idx)})\n"
    )
    return 0


def _render_te_snapshot(model, entries, total_bytes):
    extern_int32 = sorted({e[0] for e in entries if e[0].startswith(("bias", "offsetRBias"))})
    extern_uchar = sorted({e[0] for e in entries if e[0].startswith("weight")})
    decls = []
    for u in extern_int32:
        decls.append(f"extern int32_t {u}[];")
    for u in extern_uchar:
        decls.append(f"extern unsigned char {u}[];")
    extern_block = "\n".join(decls)
    table_lines = []
    for u, nb, ih, iw, alias in entries:
        table_lines.append(f"    X({u:<18}, {nb:>6}, {ih}, {iw}) /* {alias} */ \\")
    table_block = "\n".join(table_lines)
    return f"""/*
 * codegen-{model}/source/te_snapshot.c
 * Auto-generated by tools/extract_snapshot.py — do not edit by hand.
 * Regenerate by running `mise run codegen [{model}]` or by re-invoking the
 * script directly: `python tools/extract_snapshot.py {model}`.
 *
 * Covers every v* tensor that gets mutated by invoke(labels) — both biases
 * with `-=` updates and weights touched by the sparse update kernels.
 * Total snapshot size: {total_bytes} bytes.
 */
#include <stdint.h>

{extern_block}

#define TRAINABLES(X) \\
{table_block}

#define TRAINABLE_SNAP_BYTES {total_bytes}

static unsigned char s_snap[TRAINABLE_SNAP_BYTES];
static int s_snap_taken = 0;

static const struct {{ void *ptr; unsigned int bytes; unsigned char is_head; unsigned char is_weight; }} s_trainables[] = {{
#define E(arr, nb, head, weight) {{ (void*)arr, nb, head, weight }},
    TRAINABLES(E)
#undef E
}};
#define NUM_TRAINABLES ((int)(sizeof(s_trainables) / sizeof(s_trainables[0])))

void te_snapshot_weights(void) {{
    unsigned int off = 0;
    for (int i = 0; i < NUM_TRAINABLES; i++) {{
        unsigned int nb = s_trainables[i].bytes;
        unsigned char *dst = s_snap + off;
        const unsigned char *src = (const unsigned char *)s_trainables[i].ptr;
        for (unsigned int j = 0; j < nb; j++) dst[j] = src[j];
        off += nb;
    }}
    s_snap_taken = 1;
}}

void te_reset_weights_to_initial(void) {{
    if (!s_snap_taken) return;
    unsigned int off = 0;
    for (int i = 0; i < NUM_TRAINABLES; i++) {{
        unsigned int nb = s_trainables[i].bytes;
        const unsigned char *src = s_snap + off;
        unsigned char *dst = (unsigned char *)s_trainables[i].ptr;
        for (unsigned int j = 0; j < nb; j++) dst[j] = src[j];
        off += nb;
    }}
}}

int te_snapshot_ready(void) {{ return s_snap_taken; }}

void te_get_train_debug(int32_t *out) {{
    if (!out) return;
    int64_t total_changed = 0, total_abs = 0;
    int64_t hw_changed = 0, hw_abs = 0, hb_changed = 0, hb_abs = 0;
    int64_t bw_changed = 0, bw_abs = 0, bb_changed = 0, bb_abs = 0;
    uint32_t all_hash = 2166136261u, hw_hash = 2166136261u, hb_hash = 2166136261u;
    uint32_t bw_hash = 2166136261u, bb_hash = 2166136261u;

    unsigned int off = 0;
    for (int i = 0; i < NUM_TRAINABLES; i++) {{
        unsigned int nb = s_trainables[i].bytes;
        const unsigned char *cur = (const unsigned char *)s_trainables[i].ptr;
        const unsigned char *snap = s_snap + off;
        int is_head = s_trainables[i].is_head;
        int is_weight = s_trainables[i].is_weight;
        for (unsigned int j = 0; j < nb; j++) {{
            unsigned char c = cur[j];
            all_hash = (all_hash ^ c) * 16777619u;
            if (is_head && is_weight)       hw_hash = (hw_hash ^ c) * 16777619u;
            else if (is_head && !is_weight) hb_hash = (hb_hash ^ c) * 16777619u;
            else if (!is_head && is_weight) bw_hash = (bw_hash ^ c) * 16777619u;
            else                            bb_hash = (bb_hash ^ c) * 16777619u;

            if (s_snap_taken && c != snap[j]) {{
                int diff = (int)c - (int)snap[j];
                if (diff < 0) diff = -diff;
                total_changed++; total_abs += diff;
                if (is_head && is_weight)       {{ hw_changed++; hw_abs += diff; }}
                else if (is_head && !is_weight) {{ hb_changed++; hb_abs += diff; }}
                else if (!is_head && is_weight) {{ bw_changed++; bw_abs += diff; }}
                else                            {{ bb_changed++; bb_abs += diff; }}
            }}
        }}
        off += nb;
    }}

    out[0]  = (int32_t)total_changed;
    out[1]  = total_abs > 2000000000 ? 2000000000 : (int32_t)total_abs;
    out[2]  = (int32_t)all_hash;
    out[3]  = (int32_t)hw_changed;
    out[4]  = hw_abs > 2000000000 ? 2000000000 : (int32_t)hw_abs;
    out[5]  = (int32_t)hw_hash;
    out[6]  = (int32_t)hb_changed;
    out[7]  = hb_abs > 2000000000 ? 2000000000 : (int32_t)hb_abs;
    out[8]  = (int32_t)hb_hash;
    out[9]  = (int32_t)bw_changed;
    out[10] = bw_abs > 2000000000 ? 2000000000 : (int32_t)bw_abs;
    out[11] = (int32_t)bw_hash;
    out[12] = (int32_t)bb_changed;
    out[13] = bb_abs > 2000000000 ? 2000000000 : (int32_t)bb_abs;
    out[14] = (int32_t)bb_hash;
    out[15] = s_snap_taken;
}}
"""


def _stub_te_snapshot(model):
    return f"""/*
 * codegen-{model}/source/te_snapshot.c (stub)
 * Auto-generated by tools/extract_snapshot.py — no trainable tensors found
 * in this codegen (fwd-only triplet?). All te_snapshot_* / te_get_train_debug
 * entries are no-ops so bridge.c links uniformly across models.
 */
#include <stdint.h>

void te_snapshot_weights(void) {{}}
void te_reset_weights_to_initial(void) {{}}
int te_snapshot_ready(void) {{ return 0; }}

void te_get_train_debug(int32_t *out) {{
    if (!out) return;
    for (int i = 0; i < 16; i++) out[i] = 0;
}}
"""


if __name__ == "__main__":
    if len(sys.argv) != 2:
        sys.stderr.write(f"usage: {sys.argv[0]} <model_name>\n")
        sys.exit(2)
    sys.exit(extract(sys.argv[1]))
