[workspace]
channels = ["conda-forge"]
name = "zig-te-train1-tvm-macos"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
cmake = ">=3.18"
git = "*"
llvmdev = "14.*"
ninja = "*"
pip = "*"
pkg-config = "*"
python = "3.9.*"
